#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://peer2:8762/eureka/,http://peer1:8761/eureka/
#---
#spring:
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: peer1
#---
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2

#server:
#  port: 8761
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: peer1

---
server:
  port: 8761
spring:
  profiles: peer1
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    # The following two values indicate that it is server
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8861/eureka/

---
server:
  port: 8861
spring:
  profiles: peer2
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer2
  client:
    # The following two values indicate that it is server
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
---
spring:
  profiles:
    active: peer2
